-- create database student_management; 
use student_management;
-- create table Class(
-- id int,
-- name varchar(20)
-- );
-- create table Teacher(
-- id int,
-- name varchar(20),
-- age int,
-- country varchar(10)
-- );
